# -*- coding:utf-8 -*-
from selenium import webdriver
from selenium.webdriver.support.ui import Select
import time
import random
import random as r
import cx_Oracle    #cx_Oracle
#from Com.cardid import gennerator
# 获取手机号
def createPhone():
	prelist = ["130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "147", "150", "151", "152",
			   "153", "155", "156", "157", "158", "159", "186", "187", "188"]
	return random.choice(prelist) + "".join(random.choice("0123456789") for i in range(8))
# print(createPhone())
time.sleep(2)
def getxingming():
	a1 = ['宁']
	a2 = ['玉', '魁', '龙', '芳', '军', '玲','华','慕','试','张', '金', '李', '王', '赵', '时','如','跋','阳','斯','里']
	a3 = ['钢', '立', '玲', '好', '国', '测', '花','菁','甜','荣','冇','卯','都','明','鼎','偲','骏','萨']
	for i in range(1):
		name = r.choice(a1) + r.choice(a2) + r.choice(a3)
	return name
time.sleep(3)
d='10013327'	#d='11038360'		#'11039848'
e='Cs654321'
driver = webdriver.Chrome()
#driver.get("http://172.18.100.163:8080/loan/user/home")
#driver.get("http://172.18.100.43:8080/loan/user/home")
#driver.get("http://172.17.100.13:8080/loan/user/caslogin")
#driver.get("http://172.18.100.133:8080/loan")
#driver.get("http://172.18.100.73:8080/loan/user/caslogin")
driver.maximize_window()
'''driver.find_element_by_id("username").send_keys(d)
driver.find_element_by_id("pwd").send_keys(e)
driver.find_element_by_class_name("btn").click()
time.sleep(3)'''
driver.get("http://172.18.100.141:9083/loan/user/caslogin")
driver.find_element_by_xpath("//*[@id='username']").send_keys(d)
driver.find_element_by_xpath("//*[@id='pwd']").send_keys(e)
time.sleep(1)
driver.find_element_by_xpath("//input[@value='登录']").click()
time.sleep(5)
#driver.find_element_by_xpath("//div[2]/div[1]/div/h3[4]").click() #集成2
#driver.find_element_by_xpath("//div[2]/div[1]/div/h3[4]").click() #集成3
driver.find_element_by_id("firstMenu1").click()
time.sleep(1)
driver.find_element_by_xpath("//span[text()=' 进件申请']").click()
time.sleep(1)
product=('薪悦贷','薪悦贷','薪悦贷','薪悦贷','薪悦贷','信悦贷A','悦购贷A','保悦贷A','车主贷A','优悦贷A','优悦贷A','优悦贷A','优悦贷A','优悦贷A','巾帼贷A','巾帼贷B','优悦贷A','房悦贷A','薪悦贷','信悦贷A','悦购贷A','保悦贷A','车主贷A','优悦贷A','优悦贷A','优悦贷A','优悦贷A','优悦贷A',)
for i in range(len(product)):
	# 新增框架定义
	iframe1 = driver.find_element_by_xpath("//iframe[contains(@src,'lbTIntoInfo/prepareExecute/queryLbTIntoInfo')]")
	time.sleep(3)
	driver.switch_to.frame(iframe1)
	time.sleep(3)
	driver.find_element_by_xpath("//div[1]/div/div[3]/div[1]/a[1]").click()
	driver.switch_to.default_content()
	a = 411425197801246894
	b = getxingming()
	c=createPhone()
	time.sleep(3)
	#输入身份证号框架定义
	iframe2 =driver.find_element_by_xpath("//iframe[contains(@src,'operateBtn=add&loanType=1&tabTitle=新增进件信息&parentTitle=进件申请')]")
	driver.switch_to.frame(iframe2)
	time.sleep(2)
	driver.find_element_by_id("cardId").send_keys(a)
	driver.find_element_by_id("custName").send_keys(b)
	time.sleep(1)
	#driver.find_element_by_id("prodType").click()
	#Select(driver.find_element_by_id("prodType")).select_by_value("信贷产品")
	Select(driver.find_element_by_id('prodType')).select_by_visible_text("信贷产品")
	time.sleep(3)
	#Select(driver.find_element_by_id("prodCode")).select_by_visible_text(product[i])
	Select(driver.find_element_by_id("prodCode")).select_by_visible_text('优悦贷A')
	time.sleep(1)
	#driver.find_element_by_xpath("//body/div[3]/div[2]/form/div/div[6]/span/span/a/span[1]").click()
	driver.find_element_by_xpath("//form[@id='addNewsFormData4']/div/div[6]/span/span/a/span").click()
	time.sleep(2)
	driver.find_element_by_id("ui-id-1").click()
	driver.find_element_by_id("ok").click()
	time.sleep(10)   #输入身份证号界面，点击确认等待时间
	Select(driver.find_element_by_id("dtofamilyIsKnown")).select_by_visible_text("否")
	time.sleep(2)
	driver.find_element_by_css_selector("option[value=\"0\"]").click()
	time.sleep(2)
	driver.find_element_by_xpath("//table[@id='addNewsTableId']/tbody/tr[3]/td").click()
	time.sleep(2)
	driver.find_element_by_id("dtoloanPurpose").click()
	time.sleep(2)
	Select(driver.find_element_by_id("dtoloanPurpose")).select_by_visible_text("资金周转")
	driver.find_element_by_id("dtoloanPurposeDetail").send_keys("资金周转紧急")
	time.sleep(1)
	driver.find_element_by_id("dtominAppAmount").click()
	driver.find_element_by_id("dtominAppAmount").send_keys("50000")
	driver.find_element_by_id("dtomonthPayment").click()
	driver.find_element_by_id("dtomonthPayment").send_keys("30000")
	driver.find_element_by_id("dtoapplyPeriod").click()
	Select(driver.find_element_by_id("dtoapplyPeriod")).select_by_visible_text("18期")
	driver.find_element_by_id("dtocustomerChannel").click()
	Select(driver.find_element_by_id("dtocustomerChannel")).select_by_visible_text("58同城")
	driver.find_element_by_id("dtonation").send_keys("汉族")
	#driver.find_element_by_id("ui-id-46").click()
	driver.find_element_by_id("phometownAreacode").click()
	Select(driver.find_element_by_id("phometownAreacode")).select_by_visible_text("北京市")
	driver.find_element_by_css_selector("option[value=\"110000\"]").click()
	driver.find_element_by_id("chometownAreacode").click()
	Select(driver.find_element_by_id("chometownAreacode")).select_by_visible_text("北京市")
	driver.find_element_by_css_selector("option[value=\"110100\"]").click()
	driver.find_element_by_id("dtohometownAreacode").click()
	Select(driver.find_element_by_id("dtohometownAreacode")).select_by_visible_text("东城区")
	driver.find_element_by_css_selector("option[value=\"110101\"]").click()
	driver.find_element_by_id("dtohometownAddr").click()
	driver.find_element_by_id("dtohometownAddr").clear()
	driver.find_element_by_id("dtohometownAddr").send_keys("答复士大夫的三")
	driver.find_element_by_id("dtohDegree").click()
	Select(driver.find_element_by_id("dtohDegree")).select_by_visible_text("硕士及以上")
	driver.find_element_by_css_selector("#dtohDegree > option[value=\"1\"]").click()
	driver.find_element_by_id("dtomarrStatus").click()
	Select(driver.find_element_by_id("dtomarrStatus")).select_by_visible_text("未婚")
	driver.find_element_by_css_selector("#dtomarrStatus > option[value=\"1\"]").click()
	driver.find_element_by_xpath("(//table[@id='addNewsTableId']/tbody/tr[6]/td[2])[2]").click()
	driver.find_element_by_id("dtohasChild").click()
	Select(driver.find_element_by_id("dtohasChild")).select_by_visible_text("无")
	driver.find_element_by_id("dtoinCityYear").clear()
	driver.find_element_by_id("dtoinCityYear").send_keys("2015")
	driver.find_element_by_id("dtomobilePhone").click()
	driver.find_element_by_id("dtomobilePhone").clear()
	driver.find_element_by_id("dtomobilePhone").send_keys("18684645858")
	Select(driver.find_element_by_id("dtohasTelephone")).select_by_visible_text("无")
	driver.find_element_by_css_selector("#dtohasTelephone > option[value=\"0\"]").click()
	driver.find_element_by_id("dtoemail").click()
	driver.find_element_by_id("dtoemail").clear()
	driver.find_element_by_id("dtoemail").send_keys("ann@jieyuechina.com")
	driver.find_element_by_id("pcurrentAreacode").click()
	Select(driver.find_element_by_id("pcurrentAreacode")).select_by_visible_text("北京市")
	driver.find_element_by_css_selector("#pcurrentAreacode > option[value=\"110000\"]").click()
	driver.find_element_by_id("ccurrentAreacode").click()
	Select(driver.find_element_by_id("ccurrentAreacode")).select_by_visible_text("北京市")
	driver.find_element_by_css_selector("#ccurrentAreacode > option[value=\"110100\"]").click()
	driver.find_element_by_id("dtocurrentAreacode").click()
	Select(driver.find_element_by_id("dtocurrentAreacode")).select_by_visible_text("东城区")
	driver.find_element_by_css_selector("#dtocurrentAreacode > option[value=\"110101\"]").click()
	driver.find_element_by_id("dtocurrentAddr").click()
	driver.find_element_by_id("dtocurrentAddr").clear()
	driver.find_element_by_id("dtocurrentAddr").send_keys("都是是打发第三方")
	driver.find_element_by_id("dtohomeType").click()
	Select(driver.find_element_by_id("dtohomeType")).select_by_visible_text("无按揭购房")
	driver.find_element_by_css_selector("#dtohomeType > option[value=\"1\"]").click()
	driver.find_element_by_id("dtoafterTaxMonthlyIncome").clear()
	driver.find_element_by_id("dtoafterTaxMonthlyIncome").send_keys("50000")
	driver.find_element_by_id("dtomaxCreditAmount").clear()
	driver.find_element_by_id("dtomaxCreditAmount").send_keys("50000")
	Select(driver.find_element_by_id("dtocustomerSource")).select_by_visible_text("网络")
	driver.find_element_by_id("dtoaccount").click()
	driver.find_element_by_id("dtoaccount").send_keys("50000")
	driver.find_element_by_id("dtopassword").click()
	driver.find_element_by_id("dtopassword").send_keys("40000")
	driver.find_element_by_id("dtocaptcha").click()
	time.sleep(1)
	driver.find_element_by_id("dtocaptcha").send_keys("999")
	Select(driver.find_element_by_id("dtocreditReportState")).select_by_visible_text("否")
	Select(driver.find_element_by_id("dtocreditVersionType")).select_by_visible_text("精版")
	driver.find_element_by_id("dtoaccQCount").send_keys("0")
	driver.find_element_by_id("dtoaccCAuditCount").send_keys("0")
	driver.find_element_by_id("dtoloanAuditCount").send_keys("0")
	driver.find_element_by_id("dtocurrOverdueAmount").send_keys("0")
	driver.find_element_by_id("dtoyear5CreaditOverdueCount").send_keys("0")
	driver.find_element_by_id("dtoyear5LoanOverdueCount").send_keys("0")
	driver.find_element_by_id("dtojName").click()
	driver.find_element_by_id("dtojName").send_keys("工作单位全称")
	driver.find_element_by_id("dtojPhoneAreaCode").click()
	driver.find_element_by_id("dtojPhoneAreaCode").send_keys("010")
	driver.find_element_by_id("dtojPhone").click()
	driver.find_element_by_id("dtojPhone").send_keys("4698754")
	driver.find_element_by_css_selector("#pjAddrAreacode > option[value=\"450000\"]").click()
	Select(driver.find_element_by_id("pjAddrAreacode")).select_by_visible_text(u"天津市")
	driver.find_element_by_css_selector("#pjAddrAreacode > option[value=\"120000\"]").click()
	driver.find_element_by_id("cjAddrAreacode").click()
	Select(driver.find_element_by_id("cjAddrAreacode")).select_by_visible_text("天津市")
	driver.find_element_by_css_selector("option[value=\"120100\"]").click()
	driver.find_element_by_id("dtojAddrAreacode").click()
	Select(driver.find_element_by_id("dtojAddrAreacode")).select_by_visible_text("和平区")
	driver.find_element_by_css_selector("option[value=\"120101\"]").click()
	driver.find_element_by_id("dtojAddr").click()
	driver.find_element_by_id("dtojAddr").clear()
	driver.find_element_by_id("dtojAddr").send_keys("54000")
	Select(driver.find_element_by_id("dtojPosition")).select_by_visible_text("高层管理人员")
	time.sleep(1)
	driver.find_element_by_id("dtojEnterT").click()
	driver.switch_to.default_content()#跳出框架
	time.sleep(1)
	iframe3 =driver.find_element_by_xpath("//iframe[contains(@src,'about:blank')]")#进入一个新框架
	driver.switch_to.frame(iframe3)
	time.sleep(1)
	driver.find_element_by_xpath('//input[@id="dpTodayInput"]').click()#选择今天点击
	driver.switch_to.default_content()
	time.sleep(1)
	driver.switch_to.frame(iframe2)
	time.sleep(1)
	if product[i]=='商悦贷' :
		driver.find_element_by_id("dtojType").click()
		Select(driver.find_element_by_id("dtojType")).select_by_visible_text("民营")
	else:
		driver.find_element_by_id("dtojType").click()
		Select(driver.find_element_by_id("dtojType")).select_by_visible_text("机关及事业单位")
	time.sleep(1)
	#driver.find_element_by_id("dtojType").click()
	#driver.find_element_by_css_selector("#dtojType > option[value=\"1\"]").click()
	time.sleep(1)
	#driver.find_element_by_id("dtojPayType").click()
	Select(driver.find_element_by_id("dtojPayType")).select_by_visible_text("现金")
	time.sleep(1)
	#车主贷 保悦贷分支；
	if product[i]=='车主贷A' or product[i]=='车主贷B' :
		time.sleep(3)
		driver.find_element_by_id("dtobaccount").clear()
		driver.find_element_by_id("dtobaccount").send_keys("车主贷账号")
		driver.find_element_by_id("dtobpassword").clear()
		driver.find_element_by_id("dtobpassword").send_keys("车主贷密码")
		time.sleep(1)
	elif product[i]=='保悦贷A' or product[i]=='保悦贷B':
		time.sleep(1)
		driver.find_element_by_id("dtobaccount").clear()
		driver.find_element_by_id("dtobaccount").send_keys("车主贷账号")
		driver.find_element_by_id("dtobpassword").clear()
		driver.find_element_by_id("dtobpassword").send_keys("车主贷密码")
		time.sleep(1)
		driver.find_element_by_xpath("//div[@id='insurpolicy_info']/div[1]/a[text()='新建']").click()
		time.sleep(2)
		#新建保单信息
		#driver.find_element_by_id("dtocontractEffectDate").send_keys("2017-10-15")
		#driver.find_element_by_id("dtofirstPaymentDate").send_keys("2018-02-01")
		js1 = "document.getElementById('dtocontractEffectDate').value= '2017-10-15'"
		driver.execute_script(js1)
		js2 = "document.getElementById('dtofirstPaymentDate').value= '2018-02-01'"
		driver.execute_script(js2)
		driver.find_element_by_id("dtoinsurancePeriod").send_keys("2")
		driver.find_element_by_id("dtopayPeriod").send_keys("1")
		driver.find_element_by_id("dtoinsurancePremium").send_keys("1000")
		driver.find_element_by_id("dtoinsuranceAmount").send_keys("2000")
		Select(driver.find_element_by_id("dtopaymentMethod")).select_by_visible_text("年缴")
		driver.find_element_by_xpath("//span[text()='保存']").click()
	elif product[i]=='房悦贷A' or product[i]=='房悦贷B':
		driver.find_element_by_xpath("//div[@id='house_info']/div[1]/a[text()='新建']").click()
		time.sleep(2)
		driver.find_element_by_id("dtohouseType").click()
		time.sleep(1)
		Select(driver.find_element_by_id("dtohouseType")).select_by_visible_text("全款房")
		time.sleep(2)
		driver.find_element_by_id("dtohouseBuildArea").send_keys("100")
		driver.find_element_by_id("dtohousePrice").send_keys("20000")
		time.sleep(1)
		Select(driver.find_element_by_id("phouseAddrAreacode")).select_by_visible_text("北京市")
		time.sleep(1)
		driver.find_element_by_css_selector("#phouseAddrAreacode > option[value=\"110000\"]").click()
		time.sleep(1)
		driver.find_element_by_id("chouseAddrAreacode").click()
		Select(driver.find_element_by_id("chouseAddrAreacode")).select_by_visible_text("北京市")
		driver.find_element_by_css_selector("#chouseAddrAreacode > option[value=\"110100\"]").click()
		driver.find_element_by_id("dtohouseAddrAreacode").click()
		Select(driver.find_element_by_id("dtohouseAddrAreacode")).select_by_visible_text("东城区")
		driver.find_element_by_css_selector("#dtohouseAddrAreacode > option[value=\"110101\"]").click()
		driver.find_element_by_id("dtohouseDetailAddr").click()
		driver.find_element_by_id("dtohouseDetailAddr").send_keys("士大夫")
		driver.find_element_by_id("dtohousePurchasedYears").click()
		driver.find_element_by_id("dtohousePurchasedYears").send_keys("3")
		driver.find_element_by_id("dtohouseProRightRate").click()
		driver.find_element_by_id("dtohouseProRightRate").send_keys("44")
		driver.find_element_by_xpath("//span[text()='确定']").click()
	elif product[i]=='商悦贷' :
		driver.find_element_by_xpath("//div[@id='manage_info']/div[1]/a[text()='新建']").click()
		time.sleep(2)
		Select(driver.find_element_by_id("dtocomType")).select_by_visible_text("独资")
		#driver.find_element_by_id("dtoshareholdRatio").send_keys("50")
		Select(driver.find_element_by_id("dtocomAddr")).select_by_visible_text("自有房产")
		js3 = "document.getElementById('dtoregisterDate').value= '2017-10-15'"
		driver.execute_script(js3)
		Select(driver.find_element_by_id("dtocomEmpCount")).select_by_visible_text("10人至50人以下")
		driver.find_element_by_xpath("//span[text()='确定']").click()
	elif product[i]=='悦购贷A' :
		time.sleep(1)
		Select(driver.find_element_by_id("dtoebType")).select_by_visible_text("京东")
		driver.find_element_by_id("dtoebAccount").clear()
		driver.find_element_by_id("dtoebAccount").send_keys("悦购贷账号")
		driver.find_element_by_id("dtoebPassword").clear()
		driver.find_element_by_id("dtoebPassword").send_keys("悦购贷密码")
	#联系人信息-家庭联系人-父亲
	time.sleep(2)
	driver.find_element_by_xpath("//div[@id='contact_info']/div[1]/a[text()='新建']").click()
	time.sleep(2)
	Select(driver.find_element_by_id("dtocontactType")).select_by_visible_text("紧急联系人")
	driver.find_element_by_css_selector("#dtocontactType > option[value=\"2\"]").click()
	driver.find_element_by_id("dtoconRelation").click()
	Select(driver.find_element_by_id("dtoconRelation")).select_by_visible_text("同学")
	driver.find_element_by_id("dtoconName").click()
	driver.find_element_by_id("dtoconName").send_keys("撒旦法")
	driver.find_element_by_id("dtoconPhone").click()
	driver.find_element_by_id("dtoconPhone").send_keys(c)
	driver.find_element_by_xpath("(//button[@type='button'])[3]").click()
	time.sleep(1)
	#联系人信息-紧急联系人-朋友
	driver.find_element_by_xpath("//div[@id='contact_info']/div[1]/a[text()='新建']").click()
	time.sleep(1)
	driver.find_element_by_id("dtocontactType").click()
	Select(driver.find_element_by_id("dtocontactType")).select_by_visible_text("家庭联系人")
	driver.find_element_by_css_selector("#dtocontactType > option[value=\"3\"]").click()
	driver.find_element_by_id("dtoconRelation").click()
	Select(driver.find_element_by_id("dtoconRelation")).select_by_visible_text("父亲")
	driver.find_element_by_id("dtoconName").click()
	driver.find_element_by_id("dtoconName").clear()
	driver.find_element_by_id("dtoconPhone").click()
	driver.find_element_by_id("dtoconPhone").send_keys(c)
	driver.find_element_by_id("dtoconName").send_keys("安南")
	driver.find_element_by_xpath("(//button[@type='button'])[3]").click()
	time.sleep(1)
	#银行卡信息
	driver.find_element_by_xpath("//div[@id='bank_card_info']/div[1]/a[text()='新建']").click()
	time.sleep(1)
	driver.find_element_by_id("dtobankCardAccount").click()
	driver.find_element_by_id("dtobankCardAccount").clear()
	prelist = ["622588"]
	random.choice(prelist) + "".join(random.choice("0123456789") for i in range(10))
	cardid = random.choice(prelist) + "".join(random.choice("0123456789") for i in range(10))
	driver.find_element_by_id("dtobankCardAccount").send_keys(cardid)
	driver.find_element_by_id("dtobankCode").click()
	Select(driver.find_element_by_id("dtobankCode")).select_by_visible_text("农业银行")
	driver.find_element_by_css_selector("option[value=\"308\"]").click()
	driver.find_element_by_id("dtobankProvAreacode").click()
	Select(driver.find_element_by_id("dtobankProvAreacode")).select_by_visible_text("天津市")
	driver.find_element_by_css_selector("#dtobankProvAreacode > option[value=\"120000\"]").click()
	driver.find_element_by_id("dtobankCityAreacode").click()
	Select(driver.find_element_by_id("dtobankCityAreacode")).select_by_visible_text("天津市")
	driver.find_element_by_css_selector("#dtobankCityAreacode > option[value=\"120100\"]").click()
	driver.find_element_by_id("dtosubBranchName").click()
	driver.find_element_by_id("dtosubBranchName").clear()
	driver.find_element_by_id("dtosubBranchName").send_keys("撒地方撒")
	driver.find_element_by_id("dtosubBranchName").clear()
	driver.find_element_by_id("dtosubBranchName").send_keys("撒地方撒支行名称")
	driver.find_element_by_id("dtobankReservedPhone").click()
	driver.find_element_by_id("dtobankReservedPhone").clear()
	driver.find_element_by_id("dtobankReservedPhone").send_keys("15248795552")
	driver.find_element_by_id("dtoisLoanType").click()
	Select(driver.find_element_by_id("dtoisLoanType")).select_by_visible_text("是")
	driver.find_element_by_xpath("(//button[@type='button'])[3]").click()
	time.sleep(1)
#	driver.find_element_by_id("ui-id-44").click()
	driver.find_element_by_xpath("//a[text()='流水负债信息']").click()
	driver.find_element_by_id("dtocheMonIncome").click()
	driver.find_element_by_id("dtocheMonIncome").send_keys("60000")
	driver.find_element_by_id("doAddInto").click()
	time.sleep(5)
	driver.quit()
	'''driver.find_element_by_id("dtocreditReportState").click()
	Select(driver.find_element_by_id("dtocreditReportState")).select_by_visible_text("否")
	#driver.find_element_by_css_selector("#dtocreditReportState > option[value=\"1\"]").click()
	#driver.find_element_by_id("dtocreditVersionType").click()
	Select(driver.find_element_by_id("dtocreditVersionType")).select_by_visible_text("精版")
	#driver.find_element_by_css_selector("#dtocreditVersionType > option[value=\"0\"]").click()
	#driver.find_element_by_id("dtoaccQCount").click()
	driver.find_element_by_id("dtoaccQCount").send_keys("0")
	#driver.find_element_by_id("dtoaccCAuditCount").click()
	driver.find_element_by_id("dtoaccCAuditCount").send_keys("0")
	#driver.find_element_by_id("dtoloanAuditCount").click()
	driver.find_element_by_id("dtoloanAuditCount").send_keys("0")
	#driver.find_element_by_id("dtocurrOverdueAmount").click()
	driver.find_element_by_id("dtocurrOverdueAmount").send_keys("0")
	#driver.find_element_by_id("dtoyear5CreaditOverdueCount").click()
	driver.find_element_by_id("dtoyear5CreaditOverdueCount").send_keys("0")
	#driver.find_element_by_id("dtoyear5LoanOverdueCount").click()
	driver.find_element_by_id("dtoyear5LoanOverdueCount").send_keys("0")
	time.sleep(5)
	driver.find_element_by_id("doAddInto").click()
	time.sleep(5)
	driver.switch_to.default_content()
	time.sleep(2)'''